### ISSUE TITLE
Générer un epub

### ISSUE THREAD

**Issue by raphaeljolivet** [harobed/theorie-relative-de-la-monnaie#2]
Bonjour,

Serait il possible de générer le epub et de le rendre public ?
Je vois que Sphynx le gère nativement : "make epub"

J'ai téléchargé le source et ai essayé de le faire moi même, mais j'ai un problème de dépendance / version de Python.

Merci d'avance

**Comment by harobed** [comment]
Il faut essayer, à savoir que cette version présente dans le dépôt n'est pas complète.

Pouvez vous faire un essai ?

**Comment by harobed** [comment]
Le sujet m'intéresse mais n'est pas dans mes priorités du moment.

**Comment by raphaeljolivet** [comment]
Je pensais que la version GitHub était la source à jour.
Quelle est la source alors ?
Le fichier DocX

**Comment by M5oul** [comment]
Cette issue peut-être fermée. La génération de epub est à présent possible avec la version upstream : https://github.com/vtexier/theorie-relative-de-la-monnaie/
